// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb3sazwsCxY6a-DGHM2KxqN1wJ4Rlhn1g',
    appId: '1:1007594711313:web:c8f275b0d809f4134ec4b0',
    messagingSenderId: '1007594711313',
    projectId: 'chat-app-3967b',
    authDomain: 'chat-app-3967b.firebaseapp.com',
    storageBucket: 'chat-app-3967b.appspot.com',
    measurementId: 'G-SXSDPM6CNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhZgv8IhjIEoRSGq4zxqIsM-_dQID8S8A',
    appId: '1:1007594711313:android:39cdfe23b8fbad134ec4b0',
    messagingSenderId: '1007594711313',
    projectId: 'chat-app-3967b',
    storageBucket: 'chat-app-3967b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTezm49xZyIjrZwmZy-8Qnq6YW3GvI6-k',
    appId: '1:1007594711313:ios:89b7bf3c322e0a874ec4b0',
    messagingSenderId: '1007594711313',
    projectId: 'chat-app-3967b',
    storageBucket: 'chat-app-3967b.appspot.com',
    iosBundleId: 'com.example.minsu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTezm49xZyIjrZwmZy-8Qnq6YW3GvI6-k',
    appId: '1:1007594711313:ios:7a934e84d6e987d84ec4b0',
    messagingSenderId: '1007594711313',
    projectId: 'chat-app-3967b',
    storageBucket: 'chat-app-3967b.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
